### ISSUE TITLE
tabbing between inputs within views

### ISSUE THREAD

**Issue by brandonmp** [oliviertassinari/react-swipeable-views#42]
Here is normal behavior.  I click the button, screen slides entirely to next view:
![gifrecord_2016-03-11_180949](https://cloud.githubusercontent.com/assets/14139991/13718108/c29ee512-e7b4-11e5-816b-7417909f9391.gif)

Here is problematic behavior.  I tab away from the last input on the view, and it slides half-way to the next view

![gifrecord_2016-03-11_181033](https://cloud.githubusercontent.com/assets/14139991/13718117/df40bc18-e7b4-11e5-98d6-3d0767ccc23f.gif)

So one looks like a bug (the fact that the slide only gets halfway on the tab event), and the other is something I'm hoping to accomplish (preventing user from tabbing to next view altogether--limiting transition events only to the pre-defined buttons, clicks, etc.)

the structure in the code is pretty straightforward:

``` jsx
<SwipeableViews>
  <div1>
    <input1 />
    <input2 />
  </div1>
  <div2>
    <input3 />
  </div2>
</SwipeableViews>
```

Tabbing between input 2 and 3 forces a 1/2 transition from div1 to div2/.  my goal is to prevent it from causing any transition at all.

**Comment by oliviertassinari** [comment]
@brandonmp I'm not sure to understand your issue. Could you post a gif or submit a small code that explains your issue?

**Comment by brandonmp** [comment]
sure--in this gif, i tab between two fields in a child of <SwipeableViews>.  

When I tab away from the second field, it tries to slide to the next View (which isn't intended), and only gets halfway there.



![gifrecord_2016-03-11_161153](https://cloud.githubusercontent.com/assets/14139991/13715639/1e50f9e2-e7a4-11e5-8f57-3710b513f353.gif)

**Comment by oliviertassinari** [comment]
I still don't get it. How is this linked to my component? That looks like a normal behavior of a regular dom element.

**Comment by brandonmp** [comment]
sure-sorry, i'm not sure how to quickly setup a repo to demonstrate this, but here are some perhaps more illustrative gifs

Here is normal behavior.  I click the button, screen slides entirely to next view:
![gifrecord_2016-03-11_180949](https://cloud.githubusercontent.com/assets/14139991/13718108/c29ee512-e7b4-11e5-816b-7417909f9391.gif)


Here is problematic behavior.  I tab away from the last input on the view, and it slides half-way to the next view

![gifrecord_2016-03-11_181033](https://cloud.githubusercontent.com/assets/14139991/13718117/df40bc18-e7b4-11e5-98d6-3d0767ccc23f.gif)



So one looks like a bug (the fact that the slide only gets halfway on the tab event), and the other is something I'm hoping to accomplish (preventing user from tabbing to next view altogether--limiting transition events only to the pre-defined buttons, clicks, etc.)

**Comment by brandonmp** [comment]
the structure in the code is pretty straightforward:

````
<SwipeableViews>
  <div1>
    <input1 />
    <input2 />
  </div1>
  <div2>
    <input3 />
  </div2>
</SwipeableViews>
````

Tabbing between input 2 and 3 forces a 1/2 transition from div1 to div2

**Comment by oliviertassinari** [comment]
Thank for prividing more details here. I would say that it's a bug. At first glance, that looks tricky to solve.

**Comment by brandonmp** [comment]
thanks @oliviertassinari 

in the mean time, if anyone else has this problem, here's my temp workaround:

original code:
````
<SwipeableViews>
  <div1>
    <input1 />
    <input2 />
  </div1>
  <div2>
    <input3 />
  </div2>
</SwipeableViews>
````

we do 2 things: assign a ref to the last input in a view, then setup a function handler to focus that component onBlur.  so:

````
<SwipeableViews>
  <div1>
    <input1 />
    <input2 
        ref={(ref) => this.lastInput = ref}
        onBlur={this.reFocus}        
    />
  </div1>
  <div2>
    <input3 />
  </div2>
</SwipeableViews>
````

then our event handler:
````
 reFocus: function() {
        this.lastInput.focus();
    },
````

**Comment by oliviertassinari** [comment]
Regarding how we can more reliability fix this issue.
I think that we would have to listen to the `scroll` event. See what is going on and change the index if this is needed. We definitely don't when to end up between two slides.

**Comment by andrzey** [comment]
But wont this make it impossible for any other input to have focus? How is input 3 or input1 going to be able to be focused if input2 gets focus in the onBlur-function?

**Comment by andrzey** [comment]
Is a scroll-event being fired when an input gets focus on a different slide @oliviertassinari ? I havent been able to see that yet.

**Comment by oliviertassinari** [comment]
> Is a scroll-event being fired when an input gets focus on a different slide

@andrzey Good question, I have investigated.

**Comment by brandonmp** [comment]
@andrzey yeah you're correct. shortly after i implemented that fix I realized that problem, so I ended up just going w/ a more traditional routing setup for my form pages. i'll edit that post to reflect the limitation--thanks!

**Comment by andrzey** [comment]
@oliviertassinari check out ErlendWade´s fix on the tabbing-issue. I implemented it in my solution and it worked. Would be nice to have it in the npm-project.

**Comment by darioseidl** [comment]
We are also affected by this bug. Is there any news on it, or did anyone found a satisfactory workaround?

**Comment by oliviertassinari** [comment]
The solution started here https://github.com/oliviertassinari/react-swipeable-views/pull/79/commits/e912808205a6daf2450c3e80d94d230372d22510 was interesting.
I think that using the `onScroll` event is our best option.

**Comment by darioseidl** [comment]
Awesome, thank you! It's working as expected in 0.10.3 for us.

**Comment by nimahkh** [comment]
i still have this problem, my auto slider is half-way . 
material-ui : 3.7.1
lab : 3.0.0-alpha.16
